session_name: Zeeko
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: src
  focus: True
  shell_command_before:
    - workon -n Zeeko
  panes:
    - pane
- window_name: test
  shell_command_before:
    - workon -n Zeeko
  panes:
    - watching_testrunner -b zeeko -p '*.p*' -- python setup.py build_docs test
- window_name: testing
  layout: even-horizontal
  shell_command_before:
    - workon -n Zeeko
  panes:
    - pane
    - pane
    - pane